apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: node2
  namespace: tink-system
spec:
  disks:
    - device: /dev/sda
    - device: /dev/sdb
  metadata:
    facility:
      facility_code: pod15
    manufacturer:
      slug: pod15
    instance:
      userdata: "sdp"
      hostname: "node2"
      id: "b4:96:91:d6:9e:a4"
      operating_system:
        distro: "clear"
        os_slug: "clear37710"
        version: "37710"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: node2
        iface_name: enp23s0f0
        ip:
          address: 10.10.150.182
          gateway: 10.10.150.1
          netmask: /24
        lease_time: 86400
        mac: b4:96:91:d6:9e:a4
        name_servers:
          - 8.8.8.8
          - 8.8.4.4
        uefi: true
      netboot:
        allowPXE: false
        allowWorkflow: false
#        ipxe: {
#            contents: "#!ipxe",
#            url: "http://url/menu.ipxe"
#:wq
#}
        osie: {
            baseURL: "",
            initrd: "initramfs-x86_64",
            kernel: "vmlinuz-x86_64"
        }
    - dhcp:
        arch: x86_64
        hostname: node2
        iface_name: enp23s0f1
        ip:
          address: 10.10.151.22
          gateway: 10.10.150.1
          netmask: 255.255.255.0
        lease_time: 86400
        mac:  b4:96:91:d6:9e:a5
        name_servers:
          - 8.8.8.8
          - 8.8.4.4
        uefi: true
      netboot:
        allowPXE: false
        allowWorkflow: false
    - dhcp:
        arch: x86_64
        hostname: node2
        iface_name: enp49s0f0
        ip:
          address: 10.10.152.22
          gateway: 10.10.152.24
          netmask: 255.255.255.0
        lease_time: 86400
        mac: 40:a6:b7:2d:ed:c4
        name_servers:
          - 8.8.8.8
          - 8.8.4.4
        uefi: true
      netboot:
        allowPXE: true
        allowWorkflow: true
    - dhcp:
        arch: x86_64
        hostname: node2
        iface_name: enp49s0f1
        ip:
          address: 10.10.153.22
          gateway: 10.10.150.1
          netmask: 255.255.255.0
        lease_time: 86400
        mac: 40:a6:b7:2d:ed:c5
        name_servers:
          - 8.8.8.8
          - 8.8.4.4
        uefi: true
      netboot:
        allowPXE: false
        allowWorkflow: false

